### ISSUE TITLE
Deployment of rest-server leaves install directories behind in /usr/local/bin

### ISSUE THREAD

**Issue by mika** [donat-b/ansible-restic-rest#22]
The presence of directories like `rest-server_0.13.0_linux_amd64` in the `restic_install_path` (being `/usr/local/bin` by default)  was unexpected for me:

```
synpromika@backup ~ % ls -la /usr/local/bin
total 38208
[...]
lrwxrwxrwx  1 root staff       57 Aug  5  2024 rest-server -> /usr/local/bin/rest-server_0.13.0_linux_amd64/rest-server
-rwxr-xr-x  1 root root   6180576 Oct 19  2017 rest-server-0.9.5-linux-amd64
-rwxr-xr-x  1 root root   6965760 Aug  5  2019 rest-server-0.9.7
drwxr-sr-x  2 root staff     4096 Jul  8  2021 rest-server_0.10.0_linux_amd64
drwxr-sr-x  2 root staff     4096 Jun  1  2022 rest-server_0.11.0_linux_amd64
drwxr-sr-x  2 root staff     4096 Jul 20  2024 rest-server_0.12.1_linux_amd64
drwxr-sr-x  2 root staff     4096 Aug  5  2024 rest-server_0.13.0_linux_amd64

synpromika@backup ~ % ls /usr/local/bin/rest-server_0.13.0_linux_amd64
CHANGELOG.md  LICENSE  README.md  rest-server
```

It might make sense to use a deployment strategy similar to what paulfantom did in his ansible-restic role?

Quoting from https://github.com/paulfantom/ansible-restic/blob/master/tasks/install.yml:

```
- name: Download client binary
  become: false
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ go_arch }}.bz2"
    dest: "/tmp/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ go_arch }}.bz2"
    checksum: "sha256:{{ restic_checksum }}"
  delegate_to: localhost
  check_mode: false
  changed_when: false

- name: Decompress the binary
  become: false
  shell: "bzip2 -dc /tmp/restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ go_arch }}.bz2 > /tmp/restic_{{ restic_version }}_{{ go_arch }}"
  args:
    creates: "/tmp/restic_{{ restic_version }}_{{ go_arch }}"
  delegate_to: localhost
  check_mode: false
  changed_when: false

- name: Propagate restic binary
  copy:
    src: "/tmp/restic_{{ restic_version }}_{{ go_arch }}"
    dest: '{{ restic_install_path }}/restic'
    mode: '0750'
    owner: 'root'
    group: '{{ restic_group }}'
```

Thanks for your ansible role!
